UrIU/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("backend.urls")),
]

backend/forms.py
from django import forms
from .models import Contact

class QabulForm(forms.Form):
    full_name = forms.CharField(label="To'liq ismi", max_length=255)
    passport = forms.CharField(label='Passport seriyasi', max_length=20)
    viloyat = forms.CharField(label='Viloyat', max_length=255)
    tuman = forms.CharField(label='Tuman', max_length=255)
    mfy = forms.CharField(label='MFY', max_length=255)
    kucha = forms.CharField(label='Kucha', max_length=255)
    uy = forms.CharField(label='Uy', max_length=255)
    phone_number = forms.CharField(label='Telefon raqami', max_length=15)
    
    birthday = forms.DateField(label="Tug'gilgan kuni", widget=forms.DateInput(attrs={'type': 'date'}))
    school = forms.CharField(label='Tugatgan ta’lim muassasasi', max_length=255)
    attestat = forms.CharField(label="Diplom yoki attestat raqami: № ", max_length=255)
    languages = forms.CharField(label="Qaysi chet til(lar)ini o‘qigan", max_length=255)
    father = forms.CharField(label="Otasi", max_length=255)
    father_address = forms.CharField(label="Doimiy yashash manzili", max_length=255)
    father_job = forms.CharField(label="Doimiy ish joyi", max_length=255)
    father_phone_number = forms.CharField(label="Telefon raqami", max_length=15)
    
    mother = forms.CharField(label="Onasi", max_length=255)
    mother_address = forms.CharField(label="Doimiy yashash manzili", max_length=255)
    mother_job = forms.CharField(label="Doimiy ish joyi", max_length=255)
    mother_phone_number = forms.CharField(label="Telefon raqami", max_length=15)
    directions = forms.ChoiceField(
        label="Yo'nalish", 
        choices=[
            ("60110400 - Boshlang'ich ta'lim", "60110400 - Boshlang'ich ta'lim"),
            ("60220300 - Tarix", "60220300 - Tarix"),
            ("60230100 - Filoligiya va tillarni o'qitish(o'zbek tili)", "60230100 - Filoligiya va tillarni o'qitish(o'zbek tili)"),
            ("60230100 - Filoligiya va tillarni o'qitish(Ingliz tili)", "60230100 - Filoligiya va tillarni o'qitish(Ingliz tili)"),
            ("60230100 - Filoligiya va tillarni o'qitish(Rus tili)", "60230100 - Filoligiya va tillarni o'qitish(Rus tili)"),
            ("60410600 - Bank ishi", "60410600 - Bank ishi"),
            ("60410200 - Buxgalteriya hisobi", "60410200 - Buxgalteriya hisobi"),
            ("60610100 - Axborot tizimlari va texnologiyalar", "60610100 - Axborot tizimlari va texnologiyalar"),
            ("60410100 - Iqtisodiyot", "60410100 - Iqtisodiyot"),
            ("60310300 - Psixologiya", "60310300 - Psixologiya"),
            ("70220301 - Tarix", "70220301 -  Tarix"),
            ("70230101 - Lingvistika(o'zbek tili)", "70230101 -  Lingvistika(o'zbek tili)"),
            ("70230101 - Lingvistika(ingliz tili)", "70230101 -  Lingvistika(ingliz tili)"),
            ("70230101 - Lingvistika(rus tili)", "70230101 -  Lingvistika(rus tili)"),
        ],
    )
    education_type = forms.ChoiceField(
        label="Ta'lim shakli",
        choices=[
            ('Kunduzgi', 'Kunduzgi'),
            ('Sirtqi', 'Sirtqi'),
        ]
    )


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'phone', 'directions', 'education_type']

templates/qabul/base.html
{% load static %}
<!DOCTYPE html>
<html class="wide wow-animation scrollTo" lang="en">
  <head>
    <!-- Site Title-->
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="format-detection" content="telephone=no">
    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="keywords" content="intense web design multipurpose template">
    <meta name="date" content="Dec 26">
    <link rel="icon" href="{% static 'images/logo_new.png' %}" type="image/x-icon">
    <!-- Stylesheets-->
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans:400,300italic,300,400italic,600,700%7CMerriweather:400,300,300italic,400italic,700,700italic">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
  </head>
<body>
  <div class="preloader"> 
    <div class="preloader-body">
      <div class="cssload-container">
        <div class="cssload-speeding-wheel"></div>
      </div>
      <p>Loading...</p>
    </div>
  </div>
  <div class="page text-center">
    {% block body %}{% endblock %}
  </div>
  
</body>
</html>

templates/qabul/document.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>{{ qabul.phone }}</h2>
<section class="section icon-list section-lg bg-default">
    <div class="container">
        <div class="col-md-4 col-lg-3 col-sm-6" href="/media/contract/{{qabul.passport}}.docx" >
            <div class="unit unit-spacing-xsm flex-row align-items-center">
                <div class="unit-left"><span class="icon icon-madison mdi mdi-file-document"></span></div>
                <div class="unit-body">
                    <p><a href="/media/contract/{{qabul.passport}}.docx">Shartnoma</a></p>
                </div>
            </div>
            <div class="unit unit-spacing-xsm flex-row align-items-center">
                <div class="unit-left"><span class="icon icon-madison mdi mdi-file-document"></span></div>
                <div class="unit-body">
                    <p><a href="/media/application/{{qabul.passport}}.docx">Ariza</a></p>
                </div>
            </div>
        </div>
    </div>
</section>
{% include "./footer.html" %}
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/error.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>Error</h2>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/footer.html
{% load static %}
{% load my_tags %}
<footer class="page-footer">
  <div class="hr bg-gray-light"></div>
  <div class="container section-xs block-after-divider">
    <div class="row row-50 justify-content-xl-between justify-content-sm-center">
      <div class="col-lg-3 col-xl-2">
        <!--Footer brand--><a class="d-inline-block" href="index.html"><img width='170' height='170'
            src="{% static 'images/logo.png' %}" alt='' />
          <div>
            <h6 class="barnd-name fw-bold offset-top-25">{% call_get_text 'title-1' language True%}</h6>
          </div>
          <div>
            <p class="brand-slogan text-gray fst-italic font-accent">{% call_get_text 'title-2' language True%}</p>
          </div>
        </a>
      </div>
      <div class="col-sm-10 col-lg-5 col-xl-4 text-xl-start">
        <h6 class="fw-bold">{% call_get_text 'contact' language True%}</h6>
        <div class="text-subline"></div>
        <div class="offset-top-30">
          <ul class="list-unstyled contact-info list">
            <li>
              <div class="unit flex-row align-items-center unit-spacing-xs">
                <div class="unit-left"><span class="icon mdi mdi-phone align-middle icon-xs text-madison"></span></div>
                <div class="unit-body"><a class="text-dark" href="tel:+998904362022">+998-90-436-20-22</a><br> <a
                    class="d-block d-lg-inline-block text-dark" href="tel:+998914362022">+998-91-436-20-22</a>
                </div>
              </div>
            </li>
            <li class="offset-top-15">
              <div class="unit flex-row align-items-center unit-spacing-xs">
                <div class="unit-left"><span class="icon mdi mdi-map-marker align-middle icon-xs text-madison"></span>
                </div>
                <div class="unit-body text-start"><a class="text-dark" href="https://www.google.com/maps?ll=41.570595,60.614984&z=14&t=m&hl=ru&gl=US&mapclient=embed&cid=4823893255036828626">{% call_get_text 'address' language True%}</a></div>
              </div>
            </li>
            <li class="offset-top-15">
              <div class="unit flex-row align-items-center unit-spacing-xs">

              </div>
            </li>
          </ul>
        </div>
        <div class="offset-top-15 text-start">
          <ul class="list-inline list-inline-xs list-inline-madison">
            <li><a class="icon icon-xxs fa fa-facebook icon-circle icon-gray-light-filled" href="https://www.facebook.com/profile.php?id=100091826560046"></a></li>
            <li><a class="icon icon-xxs fa fa-youtube icon-circle icon-gray-light-filled" href="https://www.youtube.com/@uriu/about"></a></li>
            <li><a class="icon icon-xxs fa fa-telegram icon-circle icon-gray-light-filled" href="https://t.me/urganch_iu"></a></li>
            <li><a class="icon icon-xxs fa fa-instagram icon-circle icon-gray-light-filled" href="http://instagram.com/urganch_innovatsion_university"></a></li>
          </ul>
        </div>
      </div>
      <div class="col-sm-10 col-lg-8 col-xl-4 text-xl-start b-r-h" style="padding: 0 !important;">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6380.52755843208!2d60.60032661091538!3d41.56595516206249!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x41dfcfa155e57805%3A0x42f1e95b7cdf7bd2!2sUrganch%20innovatsion%20universiteti!5e0!3m2!1sru!2s!4v1710843889871!5m2!1sru!2s" width="400" height="280" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
  </div>
  <div class="bg-madison context-dark">
    <div class="container text-lg-start section-5">
      <p class="rights">
        © 2024. All rights reserved. Created by <a href="tel:+998907269080">Shohzod Allayarov</a>, <a href="tel:+998904346434">Zokir Abdirimov</a>
      </p>
          </span>
    </div>
  </div>
</footer>

templates/qabul/header.html
{% load static %}
{% load my_tags %}

<header class="page-head header-panel-absolute">
  <div class="rd-navbar-wrap">
    <nav class="rd-navbar rd-navbar-default" data-auto-height="false" data-lg-auto-height="true"
      data-layout="rd-navbar-fixed" data-sm-layout="rd-navbar-fixed" data-md-layout="rd-navbar-fixed"
      data-lg-layout="rd-navbar-static" data-xl-layout="rd-navbar-static" data-xxl-layout="rd-navbar-static"
      data-md-device-layout="rd-navbar-fixed" data-lg-device-layout="rd-navbar-static"
      data-xl-device-layout="rd-navbar-static" data-xxl-device-layout="rd-navbar-static" data-lg-stick-up-offset="210px"
      data-xl-stick-up-offset="85px" data-xxl-stick-up-offset="85px" data-lg-stick-up="true" data-xl-stick-up="true"
      data-xxl-stick-up="true">
      <div class="rd-navbar-inner">
        <div class="rd-navbar-panel">
          <button class="rd-navbar-toggle"
            data-rd-navbar-toggle=".rd-navbar, .rd-navbar-nav-wrap"><span></span></button>
          <h4 class="panel-title d-lg-none">{% call_get_text "Home" language True%}</h4>
          <!-- RD Navbar Right Side Toggle-->
          <button class="rd-navbar-top-panel-toggle d-lg-none"
            data-rd-navbar-toggle=".rd-navbar-top-panel"><span></span></button>
          <div class="rd-navbar-top-panel">
            <div class="rd-navbar-top-panel-left-part">
              <ul class="list-unstyled">
                <li>
                  <div class="unit flex-row align-items-center unit-spacing-xs">
                    <div class="unit-left"><span class="icon mdi mdi-phone align-middle"></span></div>
                    <div class="unit-body"><a href="tel:+998904362022">+998-90-436-20-22,</a> <a class="d-block d-lg-inline-block"
                      href="tel:+998914362022">+998-91-436-20-22</a>
                    </div>
                  </div>
                </li>
                <li>
                  <div class="unit flex-row align-items-center unit-spacing-xs">
                    <div class="unit-left"><span class="icon mdi mdi-map-marker align-middle"></span></div>
                    <div class="unit-body"><a href="https://www.google.com/maps?ll=41.570595,60.614984&z=14&t=m&hl=ru&gl=US&mapclient=embed&cid=4823893255036828626">{% call_get_text 'address' language True%}</a></div>
                  </div>
                </li>
                <li>
                  <div class="unit flex-row align-items-center unit-spacing-xs">
                  </div>
                </li>
              </ul>
            </div>
            
          </div>
        </div>
        <div class="rd-navbar-menu-wrap clearfix">
          <!--Navbar Brand-->
          <div class="rd-navbar-brand"><a class="d-inline-block" href="/{{language}}">
              <div class="unit align-items-sm-center unit-xl unit-spacing-custom">
                <div class="unit-left"><img width='171' height='171' src="{% static 'images/logo.png' %}" alt='' />
                </div>
                <div class="unit-body">
                  <div class="rd-navbar-brand-title">{% call_get_text "title-1" language True%}</div>
                  <div class="rd-navbar-brand-slogan">{% call_get_text "title-2" language True%}</div>
                </div>
              </div>
            </a></div>
          <div class="rd-navbar-nav-wrap">
            <div class="rd-navbar-mobile-scroll">
              <div class="rd-navbar-mobile-header-wrap">
                <!--Navbar Brand Mobile-->
                <div class="rd-navbar-mobile-brand"><a href="/{{language}}"><img width='136' height='138'
                      src="{% static 'images/logo.png' %}" alt='' /></a></div>
              </div>
              <!-- RD Navbar Nav-->
              
              
            </div>
            <div>
              <!-- Add Logout Button -->
              <form id="logout-form" method="post" action="/admin/logout/">
                {% csrf_token %}
                <button type="submit">Chiqish</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

templates/qabul/qabul.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<div class="containerr">
    <h2>Ma'lumotlarni kiriting</h2>
    <form method="post">
        {% csrf_token %}
        <div class="row align-items-center">
            <div class="col-6"><label for="id_full_name">To'liq ismi:</label></div>
            <div class="col-6 text-start">{{ form.full_name }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_passport">Passport seriyasi:</label></div>
            <div class="col-6 text-start">{{ form.passport }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_viloyat">Viloyat:</label></div>
            <div class="col-6 text-start">{{ form.viloyat }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_tuman">Tuman:</label></div>
            <div class="col-6 text-start">{{ form.tuman }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mfy">MFY:</label></div>
            <div class="col-6 text-start">{{ form.mfy }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_kucha">Kucha:</label></div>
            <div class="col-6 text-start">{{ form.kucha }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_uy">Uy:</label></div>
            <div class="col-6 text-start">{{ form.uy }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.phone_number }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_birthday">Tug'gilgan kuni:</label></div>
            <div class="col-6 text-start">{{ form.birthday }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_school">Tugatgan ta’lim muassasasi:</label></div>
            <div class="col-6 text-start">{{ form.school }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_attestat">Diplom yoki attestat raqami:</label></div>
            <div class="col-6 text-start">{{ form.attestat }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_languages">Qaysi chet til(lar)ini o‘qigan:</label></div>
            <div class="col-6 text-start">{{ form.languages }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father">Otasi:</label></div>
            <div class="col-6 text-start">{{ form.father }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_address">Doimiy yashash manzili:</label></div>
            <div class="col-6 text-start">{{ form.father_address }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_job">Doimiy ish joyi:</label></div>
            <div class="col-6 text-start">{{ form.father_job }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_father_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.father_phone_number }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother">Onasi:</label></div>
            <div class="col-6 text-start">{{ form.mother }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_address">Doimiy yashash manzili:</label></div>
            <div class="col-6 text-start">{{ form.mother_address }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_job">Doimiy ish joyi:</label></div>
            <div class="col-6 text-start">{{ form.mother_job }}</div>
        </div>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_mother_phone_number">Telefon raqami:</label></div>
            <div class="col-6 text-start">{{ form.mother_phone_number }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_directions">Yo'nalish:</label></div>
            <div class="col-6 text-start">{{ form.directions }}</div>
        </div>
        <br>
        <div class="row align-items-center">
            <div class="col-6"><label for="id_education_type">Ta'lim shakli:</label></div>
            <div class="col-6 text-start">{{ form.education_type }}</div>
        </div>
        <br>
        <button type="submit">Jo'natish</button>
    </form>
</div>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}

templates/qabul/success.html
{% extends "./base.html" %}
{% load static %}
{% load my_tags %}

{% block title %}{% call_get_text "Qabul" language True%}{% endblock %}

{% block body %}

{% include "./header.html" %}
<h2>Success</h2>

{% include "./footer.html" %}

<!-- Java script-->
<script src="{% static 'js/core.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}